[assets.package]
name = "Example Workspace Package"
environment = "production"
description = "Longform description"
icon = "package/icon.png"
model = "package.rbxm"

[assets.plugin]
name = "Example Workspace Plugin"
environment = "production"
description = "Longform description"
icon = "plugin/icon.png"
model = "plugin.rbxm"
type = "Plugin"

[environments.production]
creatorId = 8701739411
creatorType = "User"
universeId = 8046529594
placeId = 87060735635538
