[asset]
name = "Display Name"
description = "Longform description"
icon = "icon.png"
distribute = true

[deployment]
creatorId = 35175308
creatorType = "Group"
universeId = 7854970752
placeId = 119490202754966
