[asset]
name = "Display Name"
description = "Longform project description"
icon = "img/icon.png"
distribute = true

[creator]
creatorId = 35175308
creatorType = "Group"

[tasks]
universeId = 7854970752
placeId = 119490202754966
