
[assets.package]
name = "Example Package\n(1776896861)"
environment = "production"
model = "asset.rbxm"
icon = "icon.png"
description = "Longform description\n(1776896861)"

[environments.production]
placeId = 87060735635538
creatorId = 8701739411
universeId = 8046529594
creatorType = "User"
