[assets.package]
name = "Example Package"
environment = "production"
description = "Longform description"
icon = "icon.png"
model = "asset.rbxm"

[environments.production]
creatorId = 8701739411
creatorType = "User"
universeId = 8046529594
placeId = 87060735635538
