name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: [self-hosted, generic-linux]
    container: docker.artifactory.rbx.com/rbx-lua-build-tools:v1.0.1
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: Roblox/setup-foreman@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow-external-github-orgs: true

      - name: Install dependencies
        run: lune run install

      - name: Run unit tests
        run: lune run test

  code-quality:
    runs-on: [self-hosted, generic-linux]
    container: docker.artifactory.rbx.com/rbx-lua-build-tools:v1.0.1
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: Roblox/setup-foreman@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow-external-github-orgs: true

      - name: Install dependencies
        run: lune run install

      - name: Lint
        run: lune run lint

  analyze:
    runs-on: [self-hosted, generic-linux]
    container: docker.artifactory.rbx.com/rbx-lua-build-tools:v1.0.1
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: Roblox/setup-foreman@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow-external-github-orgs: true

      - name: Install dependencies
        run: lune run install

      - name: Setup Lune typedefs
        run: lune setup

      - name: Analyze
        run: lune run analyze
