name: Release

on:
  pull_request:
  release:
    types: [published]
  push:
    branches:
      - main

jobs:
  build-standalone-zip:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      BUILD_ARTIFACT_PATH: build/rbxasset.zip
    steps:
      - uses: actions/checkout@v4

      - uses: Roblox/setup-foreman@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow-external-github-orgs: true

      - name: Install dependencies
        run: lune run install

      - name: Build
        run: lune run build

      - uses: actions/upload-artifact@v4
        with:
          path: ${{ env.BUILD_ARTIFACT_PATH }}
          name: rbxasset

      - uses: Roblox-ActionsCache/softprops-action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: ${{ env.BUILD_ARTIFACT_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
